/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * OpenAPI spec version: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.inventory.model.BaseResponse;
import com.kibocommerce.sdk.inventory.model.BinProductQuantities;
import com.kibocommerce.sdk.inventory.model.Product;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LoadBinInventoryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-25T11:19:08.239507-05:00[America/Chicago]")
public class LoadBinInventoryResponse extends BaseResponse {
  public static final String SERIALIZED_NAME_UNITS_ADDED = "unitsAdded";
  @SerializedName(SERIALIZED_NAME_UNITS_ADDED)
  private Integer unitsAdded;

  public static final String SERIALIZED_NAME_UNITS_REMOVED = "unitsRemoved";
  @SerializedName(SERIALIZED_NAME_UNITS_REMOVED)
  private Integer unitsRemoved;

  public static final String SERIALIZED_NAME_BINS_CREATED = "binsCreated";
  @SerializedName(SERIALIZED_NAME_BINS_CREATED)
  private List<String> binsCreated = null;

  public static final String SERIALIZED_NAME_PRODUCTS_CREATED = "productsCreated";
  @SerializedName(SERIALIZED_NAME_PRODUCTS_CREATED)
  private List<Product> productsCreated = null;

  public static final String SERIALIZED_NAME_BIN_QUANTITIES = "binQuantities";
  @SerializedName(SERIALIZED_NAME_BIN_QUANTITIES)
  private List<BinProductQuantities> binQuantities = null;

  public LoadBinInventoryResponse unitsAdded(Integer unitsAdded) {
    this.unitsAdded = unitsAdded;
    return this;
  }

   /**
   * Number of units added
   * @return unitsAdded
  **/
  @ApiModelProperty(value = "Number of units added")
  public Integer getUnitsAdded() {
    return unitsAdded;
  }

  public void setUnitsAdded(Integer unitsAdded) {
    this.unitsAdded = unitsAdded;
  }

  public LoadBinInventoryResponse unitsRemoved(Integer unitsRemoved) {
    this.unitsRemoved = unitsRemoved;
    return this;
  }

   /**
   * Number of removed units
   * @return unitsRemoved
  **/
  @ApiModelProperty(value = "Number of removed units")
  public Integer getUnitsRemoved() {
    return unitsRemoved;
  }

  public void setUnitsRemoved(Integer unitsRemoved) {
    this.unitsRemoved = unitsRemoved;
  }

  public LoadBinInventoryResponse binsCreated(List<String> binsCreated) {
    this.binsCreated = binsCreated;
    return this;
  }

  public LoadBinInventoryResponse addBinsCreatedItem(String binsCreatedItem) {
    if (this.binsCreated == null) {
      this.binsCreated = new ArrayList<String>();
    }
    this.binsCreated.add(binsCreatedItem);
    return this;
  }

   /**
   * Names of created bins
   * @return binsCreated
  **/
  @ApiModelProperty(value = "Names of created bins")
  public List<String> getBinsCreated() {
    return binsCreated;
  }

  public void setBinsCreated(List<String> binsCreated) {
    this.binsCreated = binsCreated;
  }

  public LoadBinInventoryResponse productsCreated(List<Product> productsCreated) {
    this.productsCreated = productsCreated;
    return this;
  }

  public LoadBinInventoryResponse addProductsCreatedItem(Product productsCreatedItem) {
    if (this.productsCreated == null) {
      this.productsCreated = new ArrayList<Product>();
    }
    this.productsCreated.add(productsCreatedItem);
    return this;
  }

   /**
   * List of products created
   * @return productsCreated
  **/
  @ApiModelProperty(value = "List of products created")
  public List<Product> getProductsCreated() {
    return productsCreated;
  }

  public void setProductsCreated(List<Product> productsCreated) {
    this.productsCreated = productsCreated;
  }

  public LoadBinInventoryResponse binQuantities(List<BinProductQuantities> binQuantities) {
    this.binQuantities = binQuantities;
    return this;
  }

  public LoadBinInventoryResponse addBinQuantitiesItem(BinProductQuantities binQuantitiesItem) {
    if (this.binQuantities == null) {
      this.binQuantities = new ArrayList<BinProductQuantities>();
    }
    this.binQuantities.add(binQuantitiesItem);
    return this;
  }

   /**
   * List of new bin product quantities
   * @return binQuantities
  **/
  @ApiModelProperty(value = "List of new bin product quantities")
  public List<BinProductQuantities> getBinQuantities() {
    return binQuantities;
  }

  public void setBinQuantities(List<BinProductQuantities> binQuantities) {
    this.binQuantities = binQuantities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoadBinInventoryResponse loadBinInventoryResponse = (LoadBinInventoryResponse) o;
    return Objects.equals(this.unitsAdded, loadBinInventoryResponse.unitsAdded) &&
        Objects.equals(this.unitsRemoved, loadBinInventoryResponse.unitsRemoved) &&
        Objects.equals(this.binsCreated, loadBinInventoryResponse.binsCreated) &&
        Objects.equals(this.productsCreated, loadBinInventoryResponse.productsCreated) &&
        Objects.equals(this.binQuantities, loadBinInventoryResponse.binQuantities) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitsAdded, unitsRemoved, binsCreated, productsCreated, binQuantities, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoadBinInventoryResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    unitsAdded: ").append(toIndentedString(unitsAdded)).append("\n");
    sb.append("    unitsRemoved: ").append(toIndentedString(unitsRemoved)).append("\n");
    sb.append("    binsCreated: ").append(toIndentedString(binsCreated)).append("\n");
    sb.append("    productsCreated: ").append(toIndentedString(productsCreated)).append("\n");
    sb.append("    binQuantities: ").append(toIndentedString(binQuantities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

